version: "3.5"

services: 
    html-tutorial:
        image: deeq/html-tutorial
        ports: 
            - 8081:80
        container_name: html-tutorial
    
    watchover:
        image: containrrr/watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        container_name: watchtower
        command: --interval 10
